spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: '!@aud221166'


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kmk930831@gmail.com
    password: lyiplkblnupbwqbu
    properties:
      mail:
        smtp:
          starttls:
            enable: true



